{% set name = "ffpiv" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ffpiv-{{ version }}.tar.gz
  sha256: 551626db1b1ff3a40f3ecc2d25875d9bc70ec1d91a127925c7e48b2b4af2e832

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.4.0,<4
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base
    - numba
    - numpy >=1.23,<2
    - pillow
    - pip
    - pooch
    - psutil
    - rocket-fft

test:
  imports:
    - ffpiv
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/localdevices/ffpiv
  summary: 'FF-PIV: Fast and Flexible Particle Image Velocimetry analysis powered by numba.'
  dev_url: https://github.com/localdevices/ffpiv
  license: AGPL-3.0-only
  license_family: GPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hcwinsemius
